#pragma once

#include "GameClient/Color.h"

// Single palette for all NGMP/GeneralsOnline UI colors so they can be overridden cleanly,
// independent of the legacy GameSpyColor palette.
enum GeneralsOnlineColors : Int
{
	GOCOLOR_SYSTEM = 0,
	GOCOLOR_WARNING,
	GOCOLOR_ERROR,
	GOCOLOR_SUCCESS,
	GOCOLOR_DEFAULT,
	GOCOLOR_CURRENTROOM,
	GOCOLOR_ROOM,
	GOCOLOR_PLAYER_NORMAL,
	GOCOLOR_PLAYER_OWNER,
	GOCOLOR_PLAYER_BUDDY,
	GOCOLOR_PLAYER_SELF,
	GOCOLOR_PLAYER_IGNORED,
	GOCOLOR_PLAYER_OFFLINE,
	GOCOLOR_CHAT_NORMAL,
	GOCOLOR_CHAT_OWNER,
	GOCOLOR_CHAT_EMOTE,
	GOCOLOR_CHAT_OWNER_EMOTE,
	GOCOLOR_CHAT_PRIVATE,
	GOCOLOR_CHAT_PRIVATE_EMOTE,
	GOCOLOR_CHAT_PRIVATE_OWNER,
	GOCOLOR_CHAT_PRIVATE_OWNER_EMOTE,
	GOCOLOR_ADMIN,
	GOCOLOR_NAME_CHANGE,
	GOCOLOR_BLOCKED,
	GOCOLOR_MAP_SELECTED,
	GOCOLOR_MAP_UNSELECTED,
	GOCOLOR_MOTD,
	GOCOLOR_MOTD_HEADING,
	GOCOLOR_LOBBY_NORMAL,
	GOCOLOR_LOBBY_ALTERNATE,
	GOCOLOR_LOBBY_CRC_MISMATCH,
	GOCOLOR_LOBBY_BUDDY_LOCKED,
	GOCOLOR_MAX
};

extern Color GeneralsOnlineColor[GOCOLOR_MAX];
