# Do we want to build extra SDK stuff or just the game binary?
option(RTS_BUILD_CORE_TOOLS "Build core tools" ON)
option(RTS_BUILD_CORE_EXTRAS "Build core extra tools/tests" OFF)
option(RTS_BUILD_ZEROHOUR "Build Zero Hour code." ON)
option(RTS_BUILD_GENERALS "Build Generals code." ON)
option(RTS_BUILD_OPTION_PROFILE "Build code with the \"Profile\" configuration." OFF)
option(RTS_BUILD_OPTION_DEBUG "Build code with the \"Debug\" configuration." OFF)
option(RTS_BUILD_OPTION_ASAN "Build code with Address Sanitizer." OFF)
option(RTS_BUILD_OPTION_VC6_FULL_DEBUG "Build VC6 with full debug info." OFF)
option(RTS_BUILD_OPTION_FFMPEG "Enable FFmpeg support" OFF)
option(RTS_BUILD_OPTION_RETAIL_COMPATIBLE_CRC "Build with CRC compatible with retail Generals 1.08, Zero Hour 1.04" ON)
option(RTS_BUILD_OPTION_PRESERVE_RETAIL_BEHAVIOR "Retain behavior present in retail Generals 1.08 and Zero Hour 1.04" ON)
option(RTS_BUILD_OPTION_RETAIL_COMPATIBLE_XFER_SAVE "Build with Xfer Save compatible with retail Generals 1.08, Zero Hour 1.04" ON)
option(RTS_BUILD_OPTION_RETAIL_COMPATIBLE_PATHFINDING "Use retail compatible pathfinding with fixed pathfinding fallback" ON)
option(RTS_BUILD_OPTION_RETAIL_COMPATIBLE_PATHFINDING_ALLOCATION "Use retail compatible pathfinding memory allocation" ON)
option(RTS_BUILD_OPTION_RETAIL_COMPATIBLE_NETWORKING "Use retail compatible networking" ON)
option(RTS_BUILD_OPTION_RETAIL_COMPATIBLE_AIGROUP "Build with AIGroup logic CRC compatible with retail Generals 1.08, Zero Hour 1.04" ON)
option(RTS_BUILD_OPTION_ENABLE_GAMETEXT_SUBSTITUTES "Provide substitute texts when labels and strings are missing in STR or CSF translation file" ON)
option(RTS_BUILD_OPTION_ENABLE_CONFIGURABLE_SHROUD "Enable configurable shroud in GlobalData" ON)
option(RTS_BUILD_OPTION_ENABLE_FILESYSTEM_EXISTENCE_CACHE "Enable cache for local file existence" ON)
option(RTS_BUILD_OPTION_PRIORITIZE_TEXTURES_BY_SIZE "Enable prioritization of textures by size" ON)
option(RTS_BUILD_OPTION_ENABLE_GUI_HACKS "Overwrite window settings until wnd data files are adapted or fixed" ON)

if(NOT RTS_BUILD_ZEROHOUR AND NOT RTS_BUILD_GENERALS)
    set(RTS_BUILD_ZEROHOUR TRUE)
    message("You must select one project to build, building Zero Hour by default.")
endif()

add_feature_info(CoreTools RTS_BUILD_CORE_TOOLS "Build Core Mod Tools")
add_feature_info(CoreExtras RTS_BUILD_CORE_EXTRAS "Build Core Extra Tools/Tests")
add_feature_info(ZeroHourStuff RTS_BUILD_ZEROHOUR "Build Zero Hour code")
add_feature_info(GeneralsStuff RTS_BUILD_GENERALS "Build Generals code")
add_feature_info(ProfileBuild RTS_BUILD_OPTION_PROFILE "Building as a \"Profile\" build")
add_feature_info(DebugBuild RTS_BUILD_OPTION_DEBUG "Building as a \"Debug\" build")
add_feature_info(AddressSanitizer RTS_BUILD_OPTION_ASAN "Building with address sanitizer")
add_feature_info(Vc6FullDebug RTS_BUILD_OPTION_VC6_FULL_DEBUG "Building VC6 with full debug info")
add_feature_info(FFmpegSupport RTS_BUILD_OPTION_FFMPEG "Building with FFmpeg support")
add_feature_info(RetailCompatibleCRC RTS_BUILD_OPTION_RETAIL_COMPATIBLE_CRC "Building with CRC compatible with retail")
add_feature_info(PreserveRetailBehavior RTS_BUILD_OPTION_PRESERVE_RETAIL_BEHAVIOR "Retaining retail behavior")
add_feature_info(RetailCompatibleXferSave RTS_BUILD_OPTION_RETAIL_COMPATIBLE_XFER_SAVE "Building with Xfer Save compatible with retail")
add_feature_info(RetailCompatiblePathfinding RTS_BUILD_OPTION_RETAIL_COMPATIBLE_PATHFINDING "Building with retail compatible pathfinding")
add_feature_info(RetailCompatiblePathfindingAllocation RTS_BUILD_OPTION_RETAIL_COMPATIBLE_PATHFINDING_ALLOCATION "Building with retail compatible pathfinding allocation")
add_feature_info(RetailCompatibleNetworking RTS_BUILD_OPTION_RETAIL_COMPATIBLE_NETWORKING "Building with retail compatible networking")
add_feature_info(RetailCompatibleAIGroup RTS_BUILD_OPTION_RETAIL_COMPATIBLE_AIGROUP "Building with AIGroup logic compatible with retail")
add_feature_info(EnableGametextSubstitutes RTS_BUILD_OPTION_ENABLE_GAMETEXT_SUBSTITUTES "Building with gametext substitutes")
add_feature_info(EnableConfigurableShroud RTS_BUILD_OPTION_ENABLE_CONFIGURABLE_SHROUD "Building with configurable shroud")
add_feature_info(EnableFilesystemExistenceCache RTS_BUILD_OPTION_ENABLE_FILESYSTEM_EXISTENCE_CACHE "Building with filesystem existence cache")
add_feature_info(PrioritizeTexturesBySize RTS_BUILD_OPTION_PRIORITIZE_TEXTURES_BY_SIZE "Building with texture prioritization by size")
add_feature_info(EnableGuiHacks RTS_BUILD_OPTION_ENABLE_GUI_HACKS "Building with GUI hacks")

if(RTS_BUILD_ZEROHOUR)
    option(RTS_BUILD_ZEROHOUR_TOOLS "Build tools for Zero Hour" ON)
    option(RTS_BUILD_ZEROHOUR_EXTRAS "Build extra tools/tests for Zero Hour" OFF)
    option(RTS_BUILD_ZEROHOUR_DOCS "Build documentation for Zero Hour" OFF)

    add_feature_info(ZeroHourTools RTS_BUILD_ZEROHOUR_TOOLS "Build Zero Hour Mod Tools")
    add_feature_info(ZeroHourExtras RTS_BUILD_ZEROHOUR_EXTRAS "Build Zero Hour Extra Tools/Tests")
    add_feature_info(ZeroHourDocs RTS_BUILD_ZEROHOUR_DOCS "Build Zero Hour Documentation")
endif()

if(RTS_BUILD_GENERALS)
    option(RTS_BUILD_GENERALS_TOOLS "Build tools for Generals" ON)
    option(RTS_BUILD_GENERALS_EXTRAS "Build extra tools/tests for Generals" OFF)
    option(RTS_BUILD_GENERALS_DOCS "Build documentation for Generals" OFF)

    add_feature_info(GeneralsTools RTS_BUILD_GENERALS_TOOLS "Build Generals Mod Tools")
    add_feature_info(GeneralsExtras RTS_BUILD_GENERALS_EXTRAS "Build Generals Extra Tools/Tests")
    add_feature_info(GeneralsDocs RTS_BUILD_GENERALS_DOCS "Build Generals Documentation")
endif()

if(NOT IS_VS6_BUILD)
    # Because we set CMAKE_CXX_STANDARD_REQUIRED and CMAKE_CXX_EXTENSIONS in the compilers.cmake this should be enforced.
    target_compile_features(core_config INTERFACE cxx_std_20)
endif()

if(IS_VS6_BUILD AND RTS_BUILD_OPTION_VC6_FULL_DEBUG)
    target_compile_options(core_config INTERFACE ${RTS_FLAGS} /Zi)
else()
    target_compile_options(core_config INTERFACE ${RTS_FLAGS})
endif()

# This disables a lot of warnings steering developers to use windows only functions/function names.
if(MSVC)
    target_compile_definitions(core_config INTERFACE _CRT_NONSTDC_NO_WARNINGS _CRT_SECURE_NO_WARNINGS $<$<CONFIG:DEBUG>:_DEBUG_CRT>)
endif()

if(UNIX)
    target_compile_definitions(core_config INTERFACE _UNIX)
endif()

if(RTS_BUILD_OPTION_DEBUG)
    target_compile_definitions(core_config INTERFACE RTS_DEBUG WWDEBUG DEBUG)
else()
    target_compile_definitions(core_config INTERFACE RTS_RELEASE NDEBUG)
endif()

if(RTS_BUILD_OPTION_PROFILE)
    target_compile_definitions(core_config INTERFACE RTS_PROFILE)
endif()

if(NOT RTS_BUILD_OPTION_RETAIL_COMPATIBLE_CRC)
    target_compile_definitions(core_config INTERFACE RETAIL_COMPATIBLE_CRC=0)
endif()

if(NOT RTS_BUILD_OPTION_PRESERVE_RETAIL_BEHAVIOR)
    target_compile_definitions(core_config INTERFACE PRESERVE_RETAIL_BEHAVIOR=0)
endif()

if(NOT RTS_BUILD_OPTION_RETAIL_COMPATIBLE_XFER_SAVE)
    target_compile_definitions(core_config INTERFACE RETAIL_COMPATIBLE_XFER_SAVE=0)
endif()

if(NOT RTS_BUILD_OPTION_RETAIL_COMPATIBLE_PATHFINDING)
    target_compile_definitions(core_config INTERFACE RETAIL_COMPATIBLE_PATHFINDING=0)
endif()

if(NOT RTS_BUILD_OPTION_RETAIL_COMPATIBLE_PATHFINDING_ALLOCATION)
    target_compile_definitions(core_config INTERFACE RETAIL_COMPATIBLE_PATHFINDING_ALLOCATION=0)
endif()

if(NOT RTS_BUILD_OPTION_RETAIL_COMPATIBLE_NETWORKING)
    target_compile_definitions(core_config INTERFACE RETAIL_COMPATIBLE_NETWORKING=0)
endif()

if(NOT RTS_BUILD_OPTION_RETAIL_COMPATIBLE_AIGROUP)
    target_compile_definitions(core_config INTERFACE RETAIL_COMPATIBLE_AIGROUP=0)
endif()

if(NOT RTS_BUILD_OPTION_ENABLE_GAMETEXT_SUBSTITUTES)
    target_compile_definitions(core_config INTERFACE ENABLE_GAMETEXT_SUBSTITUTES=0)
endif()

if(NOT RTS_BUILD_OPTION_ENABLE_CONFIGURABLE_SHROUD)
    target_compile_definitions(core_config INTERFACE ENABLE_CONFIGURABLE_SHROUD=0)
endif()

if(NOT RTS_BUILD_OPTION_ENABLE_FILESYSTEM_EXISTENCE_CACHE)
    target_compile_definitions(core_config INTERFACE ENABLE_FILESYSTEM_EXISTENCE_CACHE=0)
endif()

if(NOT RTS_BUILD_OPTION_PRIORITIZE_TEXTURES_BY_SIZE)
    target_compile_definitions(core_config INTERFACE PRIORITIZE_TEXTURES_BY_SIZE=0)
endif()

if(NOT RTS_BUILD_OPTION_ENABLE_GUI_HACKS)
    target_compile_definitions(core_config INTERFACE ENABLE_GUI_HACKS=0)
endif()
