# Generates a C++ source file embedding every non-dotfile under DATA_DIR as a table of
# { path, data, size } records, for EmbeddedArchiveFile to serve as in-memory files.
#
# Run via `cmake -P` from a custom command (see GeneralsMD/Code/Main/CMakeLists.txt),
# with DATA_DIR and OUTPUT_FILE passed in via -D. Re-run whenever the custom command's
# DEPENDS list says a Data/ file changed; the top-level glob's CONFIGURE_DEPENDS also
# triggers a reconfigure (and so a rebuild) when a file is added or removed.

if(NOT DEFINED DATA_DIR)
    message(FATAL_ERROR "GenerateEmbeddedData.cmake: DATA_DIR not set")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "GenerateEmbeddedData.cmake: OUTPUT_FILE not set")
endif()

# Bytes per line in the generated array initializers, purely for readability;
# MSVC has no issue with the resulting array as a whole, only with pathologically
# long single lines, which this avoids.
set(RTS_BYTES_PER_LINE 20)

file(GLOB_RECURSE RTS_DATA_FILES LIST_DIRECTORIES FALSE "${DATA_DIR}/*")
if(RTS_DATA_FILES)
    list(SORT RTS_DATA_FILES)
endif()

set(content "// Generated by cmake/GenerateEmbeddedData.cmake from files under Data/. Do not edit.\n")
string(APPEND content "#include \"EmbeddedDataTable.h\"\n\n")

set(table_rows "")
set(file_index 0)

foreach(data_file ${RTS_DATA_FILES})
    # Skip dotfiles (e.g. Data/.gitkeep, the placeholder that keeps the folder in git)
    # -- they are never game data and must never be embedded.
    get_filename_component(base_name "${data_file}" NAME)
    string(SUBSTRING "${base_name}" 0 1 base_name_first_char)
    if(base_name_first_char STREQUAL ".")
        continue()
    endif()

    file(RELATIVE_PATH rel_path "${DATA_DIR}" "${data_file}")

    file(READ "${data_file}" hex_content HEX)
    string(LENGTH "${hex_content}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")

    if(byte_count GREATER 0)
        string(REGEX REPLACE "(..)" "0x\\1," byte_list "${hex_content}")
        # insert a line break every RTS_BYTES_PER_LINE bytes for readability
        string(REGEX REPLACE "([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,)" "\\1\n    " byte_list "${byte_list}")
    else()
        set(byte_list "")
    endif()

    string(APPEND content "static const unsigned char s_embeddedData_${file_index}[] = { ${byte_list}\n    0 };\n\n")

    string(APPEND table_rows "    { \"${rel_path}\", s_embeddedData_${file_index}, ${byte_count}u },\n")

    math(EXPR file_index "${file_index} + 1")
endforeach()

string(APPEND content "const EmbeddedFileRecord g_embeddedDataTable[] = {\n")
if(file_index EQUAL 0)
    string(APPEND content "    { nullptr, nullptr, 0u },\n")
else()
    string(APPEND content "${table_rows}")
endif()
string(APPEND content "};\n\n")
string(APPEND content "const unsigned int g_embeddedDataCount = ${file_index}u;\n")

file(WRITE "${OUTPUT_FILE}" "${content}")

message(STATUS "GenerateEmbeddedData: embedded ${file_index} file(s) from ${DATA_DIR} into ${OUTPUT_FILE}")
