name: Build Generals with VC6

on:
  push:
    branches:
      - main
    paths:
      - "Generals/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-vc6-generals.yml"
      - ".github/workflows/build-vc6-common.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Generals/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-vc6-generals.yml"
      - ".github/workflows/build-vc6-common.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generals:
    uses: ./.github/workflows/build-vc6-common.yml
    with:
      game: "Generals"
    secrets: inherit
