name: GeneralsMD

on:
  push:
    branches:
      - main
    paths:
      - "GeneralsMD/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-generalsmd.yml"
      - ".github/workflows/toolchain-common.yml"
  pull_request:
    branches:
      - main
    paths:
      - "GeneralsMD/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-generalsmd.yml"
      - ".github/workflows/toolchain-common.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build GeneralsMD (${{ matrix.preset }})
    strategy:
      matrix:
        include:
          - preset: "vc6"
            tools: true
          - preset: "vc6prof"
            tools: true
          - preset: "vc6int"
            tools: true
          - preset: "vc6debug"
            tools: true
          # - preset: "msvc32"
          #   tools: true
          # - preset: "msvc32prof"
          #   tools: true
          # - preset: "msvc32int"
          #   tools: true
          # - preset: "msvc32debug"
          #   tools: true
      fail-fast: false
    uses: ./.github/workflows/toolchain-common.yml
    with:
      game: "GeneralsMD"
      preset: ${{ matrix.preset }}
      tools: ${{ matrix.tools }}
    secrets: inherit
