name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: ${{ matrix.preset }} ${{ matrix.game }} mode=${{ matrix.mode }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - { game: Generals, preset: vc6, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: vc6, mode: retail, tools: true, extras: true, ffmpeg: false, replays: true }
          - { game: Generals, preset: vc6-profile, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: vc6-profile, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: Generals, preset: vc6-debug, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: vc6-debug, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: vc6-releaselog, mode: retail, tools: true, extras: true, ffmpeg: false, replays: true }
          - { game: Generals, preset: win32, mode: noretail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: win32, mode: noretail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: Generals, preset: win32, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: win32, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: Generals, preset: win32-profile, mode: noretail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: win32-profile, mode: noretail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: Generals, preset: win32-profile, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: win32-profile, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: Generals, preset: win32-debug, mode: noretail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: win32-debug, mode: noretail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: Generals, preset: win32-debug, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
          - { game: GeneralsMD, preset: win32-debug, mode: retail, tools: true, extras: true, ffmpeg: false, replays: false }
    uses: ./.github/workflows/_build-toolchain.yml
    with:
      game: ${{ matrix.game }}
      preset: ${{ matrix.preset }}
      tools: ${{ matrix.tools }}
      extras: ${{ matrix.extras }}
      ffmpeg: ${{ matrix.ffmpeg }}
      retail-compatible: ${{ matrix.mode }}
      run-replay-tests: ${{ matrix.replays }}
    secrets: inherit

  build-vcpkg:
    name: ${{ matrix.preset }} ${{ matrix.game }} mode=${{ matrix.mode }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { game: Generals, preset: win32-vcpkg, mode: noretail, tools: true, extras: true, ffmpeg: false }
          - { game: Generals, preset: win32-vcpkg, mode: retail, tools: true, extras: true, ffmpeg: false }
          - { game: GeneralsMD, preset: win32-vcpkg, mode: noretail, tools: true, extras: true, ffmpeg: true }
          - { game: GeneralsMD, preset: win32-vcpkg, mode: retail, tools: true, extras: true, ffmpeg: true }
          - { game: Generals, preset: win32-vcpkg-profile, mode: noretail, tools: true, extras: true, ffmpeg: false }
          - { game: GeneralsMD, preset: win32-vcpkg-profile, mode: noretail, tools: true, extras: true, ffmpeg: false }
          - { game: Generals, preset: win32-vcpkg-profile, mode: retail, tools: true, extras: true, ffmpeg: false }
          - { game: GeneralsMD, preset: win32-vcpkg-profile, mode: retail, tools: true, extras: true, ffmpeg: false }
          - { game: Generals, preset: win32-vcpkg-debug, mode: noretail, tools: true, extras: true, ffmpeg: false }
          - { game: GeneralsMD, preset: win32-vcpkg-debug, mode: noretail, tools: true, extras: true, ffmpeg: false }
          - { game: Generals, preset: win32-vcpkg-debug, mode: retail, tools: true, extras: true, ffmpeg: false }
          - { game: GeneralsMD, preset: win32-vcpkg-debug, mode: retail, tools: true, extras: true, ffmpeg: false }
    uses: ./.github/workflows/_build-toolchain.yml
    with:
      game: ${{ matrix.game }}
      preset: ${{ matrix.preset }}
      tools: ${{ matrix.tools }}
      extras: ${{ matrix.extras }}
      ffmpeg: ${{ matrix.ffmpeg }}
      retail-compatible: ${{ matrix.mode }}
    secrets: inherit
